version: "3.3"
  
services:
  front:
    build:
      context: ./src/front
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"

    image: front

  back:
    build:
      context: ./src/back
      dockerfile: ./Dockerfile
    ports:
      - "9000:8080"

    image: back